import { Inter } from 'next/font/google';
import "./globals.css";
import Layout from "./components/Layout";

const inter = Inter({ 
  subsets: ['latin'],
  variable: '--font-inter',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
         className={`${inter.variable} bg-gray-100`}
      >
         <Layout children={children}/>
      </body>
    </html>
  );
}
